version: '3.7'

services:

  # ELK Stack Setup
  setup:
    extends:
      file: .docker/logging.yml
      service: setup

  # Elastic Search
  elasticsearch:
    extends:
      file: .docker/logging.yml
      service: elasticsearch

  # LogStash
  logstash:
    depends_on:
       - elasticsearch
    extends:
      file: .docker/logging.yml
      service: logstash

  # Kibana
  kibana:
    depends_on:
      - elasticsearch
    extends:
      file: .docker/logging.yml
      service: kibana
  
  # Heartbeat
  heartbeat:
    depends_on:
      - elasticsearch
    extends:
      file: .docker/logging.yml
      service: heartbeat

  # Database
  database:
    extends:
      file: .docker/databases.yml
      service: ${DATABASE}

  # Messaging Service
  messaging:
    extends:
      file: .docker/messaging.yml
      service: rabbitmq

  owssilo:
    image: ${REGISTRY:-ows}/owssilo:${PLATFORM:-linux}-${TAG:-latest}
    build:
      context: .
      dockerfile: OWS.API.Silo/Dockerfile
    environment:
     - OWSStorageConfig__OWSDBBackend=${DATABASE}
     - OWSStorageConfig__OWSDBConnectionString=${DATABASE_CONNECTION_STRING}
     - OWSAPIPathConfig__InternalPublicApiURL=${InternalPublicApiURL}
     - OWSAPIPathConfig__InternalInstanceManagementApiURL=${InternalInstanceManagementApiURL}
     - OWSAPIPathConfig__InternalCharacterPersistenceApiURL=${InternalCharacterPersistenceApiURL}
     - RabbitMQOptions__RabbitMQHostName=${RabbitMQHostName}
     - RabbitMQOptions__RabbitMQPort=${RabbitMQPort}
     - RabbitMQOptions__RabbitMQUserName=${RabbitMQUserName}
     - RabbitMQOptions__RabbitMQPassword=${RabbitMQPassword}
    ports:
      - "8080"
    depends_on:
      - database
      - messaging

  # OWS Public Api
  owspublicapi:
    image: ${REGISTRY:-ows}/owspublicapi:${PLATFORM:-linux}-${TAG:-latest}
    build:
      context: .
      dockerfile: OWSPublicAPI/Dockerfile
    environment:
     - OWSStorageConfig__OWSDBBackend=${DATABASE}
     - OWSStorageConfig__OWSDBConnectionString=${DATABASE_CONNECTION_STRING}
     - OWSAPIPathConfig__InternalPublicApiURL=${InternalPublicApiURL}
     - OWSAPIPathConfig__InternalInstanceManagementApiURL=${InternalInstanceManagementApiURL}
     - OWSAPIPathConfig__InternalCharacterPersistenceApiURL=${InternalCharacterPersistenceApiURL}
     - RabbitMQOptions__RabbitMQHostName=${RabbitMQHostName}
     - RabbitMQOptions__RabbitMQPort=${RabbitMQPort}
     - RabbitMQOptions__RabbitMQUserName=${RabbitMQUserName}
     - RabbitMQOptions__RabbitMQPassword=${RabbitMQPassword}
    ports:
      - "44302:80"
      - "44303:443"
    depends_on:
      - database
      - messaging
      - owssilo

networks:
  elk:
    driver: bridge
volumes:
  setup:
    name: "ows2-setup"
  elasticsearch:
    name: "ows2-elasticsearch"
  database:
    name: "ows2-database"
  messaging:
    name: "ows2-messaging"
